### ISSUE TITLE
Zero exit status returned even when steps fail

### ISSUE THREAD

**Issue by jamiebullock** [cucumber/cucumber-cpp#168]
## Summary

I'm not sure if this is an issue with cucumber-cpp or an upstream issue in Cucumber, but since I'm using cucumber-cpp, I'm reporting here first.

In summary, I am using the latest ( 0928f2568a9681291b8dff6a5fb3549305109324 ) version of cucumber-cpp and even when tests fail, cucumber returns exit status 0

## Expected Behavior

Cucumber CPP returns non-zero exit status when tests fail

## Current Behavior

~~~
~~~
Cucumber CPP returns zero exit status when tests fail

## Your Environment

* Version used:
0928f2568a9681291b8dff6a5fb3549305109324

cucumber --version
2.0.0

* Operating System and version:

macOS 10.12.6

**Comment by paoloambrosio** [comment]
I'm on holiday so can't try and reproduce the behaviour.

I suppose you are talking about [Cucumber-Ruby](https://github.com/cucumber/cucumber-ruby) returning a successful (zero) status code after execution with failing Cucumber-Cpp steps, right? The Cucumber-Cpp executable, with the C++ steps will always exit successfully even if failing steps are executed.

Have you tried with the latest 2.4.0 release? To test Cucumber-Cpp itself we have to use version 2.0.0 because the version of [Aruba](https://github.com/cucumber/aruba) we are using is not compatible with later releases, but you can use any 2.x version for your C++ projects.

**Comment by jamiebullock** [comment]
I'm very sorry, but this turned out to have been an error in my script.

I was calling cucumber from a Makefile and not capturing the exit code of the command as described [here](https://stackoverflow.com/questions/16315089/how-to-get-exit-status-of-a-shell-command-used-in-gnu-makefile). When I do that it works as expected.
