### ISSUE TITLE
QML support

### ISSUE THREAD

**Issue by MartinDelille** [cucumber/cucumber-cpp#205]
Sorry for not respecting the template but my question is simple: is there some example on using Cucumber with a Qt/QML application?

Here are some information about QML: https://doc.qt.io/qt-5.11/qtqml-index.html

**Comment by JD31** [comment]
+1!

Would be nice if available. Did you find a solution for Qml ?

**Comment by MartinDelille** [comment]
Nope.

**Comment by c4pQ** [comment]
> +1!
> 
> Would be nice if available. Did you find a solution for Qml ?

I came up with a quiet straightforward solution: calling signals and slots of QML objects from C++ side via `QMetaObject::invokeMethod` and looking for children by their `objectName`

Not that neat but works and helps to test UI.

**Comment by MartinDelille** [comment]
@c4pQ Would you share a code snippet? I'll be interested to look at it! 😄

**Comment by c4pQ** [comment]
@MartinDelille sure, but I need some time.

**Comment by jermus67** [comment]
Hello,

This issue is closed since there has not been any activity for more than a year on this issue.

I do hope that @MartinDelille and @c4pQ had contact about this issue outside the github environment in such a way that @MartinDelille would now be able to create behavior descriptions using Gherkin and provide step implementations in C++ using cucumber-cpp for applications programmed with QML.

Since the purpose of the cucumber-cpp project is to allow developers to write glue code for Gherkin steps in C++, I think that the approach of @c4pQ is the way to go in use-cases like this, i.e. using a C++ API, in this case the QML C++ API, to interact with the environment, in this QML objects.

Kind regards,
Jeroen Kouwer
