### ISSUE TITLE
Outdated links in readme

### ISSUE THREAD

**Issue by ursfassler** [cucumber/cucumber-cpp#298]
### 👓 What did you see?

Some links in the Readme are outdated.

### ✅ What did you expect to see?

- Cucumber Website -> https://cucumber.io/
- Cucumber Discussion Group -> ?
  I'd guess either https://cucumberbdd-slack-invite.herokuapp.com/ (from the website) or https://cucumber.io/community#slack (suggestion when opening a new issue within this project), but joining discussion is not possible with both links 

### 📚 Any additional context?

Came up with #297

**Comment by ursfassler** [comment]
@mpkorstanje What link should we us to join a discussion for cucumber? Do we have a solution?
I also have the old Matrix room as alternative: https://matrix.to/#/#cucumber_cucumber-cpp:gitter.im

**Comment by mpkorstanje** [comment]
Coincidentally, during today's committers call we updated the Get in Touch pages and setup a Github Discussions at the org level. So I think it would make sense to link to https://cucumber.io/docs/community/get-in-touch instead of specific items.

If you want, we could also setup a Github Discussion board for Cucumber CPP. 

I don't know aobut Matrix yet, we did talk about replacing Slack, but didn't get too deep into  that yet.
